Fix "TypeError: object is not a function"
See https://www.npmjs.com/package/babel-plugin-add-module-exports. It's
somewhat unfortunate that we're stuck using this, but we obviously can't
change the way that Hubot loads the module, so this is what we're stuck
with.

Fixes #4